name: CI/CD Pipeline for AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Set up Node.js
      uses: actions/setup-node@v4.1.0
      with:
        node-version: '16'

    - name: Install dependencies (Backend)
      working-directory: ./server
      run: npm install

    - name: Run tests (Backend)
      working-directory: ./server
      run: npm test

    - name: Install dependencies (Frontend)
      working-directory: ./shop
      run: |
        npm install
        npx update-browserslist-db@latest --update-db

    - name: Run tests (Frontend)
      working-directory: ./shop
      run: npm test

  dockerize:
    name: Dockerize and Push Images
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2

    - name: Log in to DockerHub
      uses: docker/login-action@v3.3.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/emarket-backend:latest ./server

    - name: Build and tag Frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/emarket-frontend:latest ./shop

    - name: Push Backend image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/emarket-backend:latest

    - name: Push Frontend image to DockerHub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/emarket-frontend:latest

  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest
    needs: dockerize

    steps:
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: 3.121.215.47
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        timeout: 60s
        script: |
          echo "Navigating to Docker Compose directory..."
          cd ~/emarket

          echo "Pulling updated Docker images..."
          docker pull ${{ secrets.DOCKER_USERNAME }}/emarket-backend:latest || exit 1
          docker pull ${{ secrets.DOCKER_USERNAME }}/emarket-frontend:latest || exit 1

          echo "Restarting Docker Compose services..."
          docker-compose down || true
          docker-compose up -d || exit 1

          echo "Deployment completed successfully!"